# -*- coding: utf-8 -*-
"""파이썬과제_xml정보추출.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9LS515O0LZo8NeBWUJh5ZlfR7B0euJ8
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

url = 'http://apis.data.go.kr/1613000/TrainInfoService/getStrtpntAlocFndTrainInfo'
serviceKey = 'DYj33IRmwl9dXqyedRW5+z2XlsGzUu70fvcia/jG2e6FXj/hDuUINU0Y4C0huSHnd5DmkUPVnUSRAuDj02M0Xg=='

# 출발역과 기차종류 리스트
depPlaceIds = ["NAT130104", "NAT010000", "NAT010032"]
train_grades = ["00", "01", "02"]

# 결과 append할 리스트정리
trainData = []

# 출발역과 기차종류 이중반복 통해서 api에서 xml파일 추출
for depPlace in depPlaceIds:
    for trainGrade in train_grades:
        page = 1
        while True:
            params = {
                'serviceKey': serviceKey,
                'pageNo': page,
                'numOfRows': 10,
                '_type': 'xml',
                'depPlaceId': depPlace,
                'arrPlaceId': 'NAT011668',
                'depPlandTime': '20230403',
                'trainGradeCode': trainGrade
            }

# request로 가져와서 beautifulsoup로 파서하기
            response = requests.get(url, params=params)
            soup = BeautifulSoup(response.content, "xml")
            items = soup.find_all("item")

# while문 break포인트잡아주기
            if not items:
                break

# item find.all한 items에서 태그정보가져오고, none값 설정
            for item in items:
                if item.find("trainno"):
                    trainNo = item.find("trainno").text
                else:
                    trainNo = None

                if item.find("depplacename"):
                    depPlaceName = item.find("depplacename").text
                else:
                    depPlaceName = None

                if item.find("arrplacename"):
                    arrPlaceName = item.find("arrplacename").text
                else:
                    arrPlaceName = None

                if item.find("depplandtime"):
                    depPlandTime = item.find("depplandtime").text
                else:
                    depPlandTime = None

                if item.find("arrplandtime"):
                    arrPlandTime = item.find("arrplandtime").text
                else:
                    arrPlandTime = None

                if item.find("traingradename"):
                    trainGradeName = item.find("traingradename").text
                else:
                    trainGradeName = None

                trainDic = {
                    "depPlaceId": depPlace,
                    "trainGradeCode": trainGrade,
                    "trainNo": trainNo,
                    "depPlaceName": depPlaceName,
                    "arrPlaceName": arrPlaceName,
                    "depPlandTime": depPlandTime,
                    "arrPlandTime": arrPlandTime,
                    "trainGradeName": trainGradeName
                }

                trainData.append(trainDic)

            page += 1
# 데이터프레임화
df = pd.DataFrame(trainData)

# 결과 출력 및 저장
df